aptitude:
  ubuntu: [aptitude]
arp-scan:
  ubuntu: [arp-scan]
bash-completion:
  ubuntu: [bash-completion]
clang-7:
  ubuntu: [clang-7]
clang-format-7:
  ubuntu: [clang-format-7]
clang-tidy-7:
  ubuntu: [clang-tidy-7]
grub-efi:
  ubuntu: [grub-efi]
gnupg2:
  ubuntu: [gnupg2]
iftop:
  ubuntu: [iftop]
iotop:
  ubuntu: [iotop]
iperf3:
  ubuntu: [iperf3]
libirimager:
  ubuntu: [libirimager]
libompl-dev:
  ubuntu: [libompl-dev]
libspinnaker-dev:
  ubuntu: [libspinnaker1-dev]
libxsensmt-dev:
  ubuntu: [libxsensmt-dev]
linux-lowlatency:
  ubuntu:
    bionic: [linux-image-4.15.0-48-lowlatency, linux-headers-4.15.0-48-lowlatency]
    focal: [linux-image-5.4.0-40-lowlatency, linux-headers-5.4.0-40-lowlatency]
lsb-release:
  ubuntu: [lsb-release]
ltrace:
  ubuntu: [ltrace]
nano:
  ubuntu: [nano]
nload:
  ubuntu: [nload]
pciutils:
  ubuntu: [pciutils]
python-cvxopt:
  ubuntu: [python-cvxopt]
python-igraph:
  ubuntu: [python-igraph]
python-progressbar:
  ubuntu: [python-progressbar]
python-psutil:
  ubuntu: [python-psutil]
python-rospkg:
  ubuntu: [python-rospkg]
python-serial:
  ubuntu: [python-serial]
qttools5-dev:
  ubuntu: [qttools5-dev]
shutter:
  ubuntu: [shutter]
spinview:
  ubuntu: [spinview-qt1]
strace:
  ubuntu: [strace]
sysbench:
  ubuntu: [sysbench]
systemd:
  ubuntu: [systemd]
systemd-coredump:
  ubuntu: [systemd-coredump]
ucf:
  ubuntu: [ucf]
# Fixme: packages below are a workaround for upstream ros packages not yet available in noetic. Remove once they are.
serial:
  ubuntu:
    bionic: [ros-melodic-serial]
    focal: [ros-noetic-serial]
statistics_msgs:
  ubuntu:
    bionic: [ros-melodic-statistics-msgs]
    focal: [ros-noetic-statistics-msgs]
image_exposure_msgs:
  ubuntu:
    bionic: [ros-melodic-image-exposure-msgs]
    focal: [ros-noetic-image-exposure-msgs]
wfov_camera_msgs:
  ubuntu:
    bionic: [ros-melodic-wfov-camera-msgs]
    focal: [ros-noetic-wfov-camera-msgs]
velodyne_description:
  ubuntu:
    bionic: [ros-melodic-velodyne-description]
    focal: [ros-noetic-velodyne-description]
velodyne_gazebo_plugins:
  ubuntu:
    bionic: [ros-melodic-velodyne-gazebo-plugins]
    focal: [ros-noetic-velodyne-gazebo-plugins]
