ads_root_certificate:
  ubuntu: [ads-root-certificate]
# The anymal_test_inspection_tour_sim system tests depends on the ANYmal dragon configuration.
# As it is not part of the mono-repo the database does not know about it.
# For now we add it here such that the CI finds the package.
anyauth:
  ubuntu:
    noble: [anyauth]
anycli:
  ubuntu:
    noble: [python3-anybotics.anycli]
anymal_config_dragon:
  ubuntu:
    focal: [ros-noetic-anymal-config-dragon]
anymal_config_interface:
  ubuntu: [anymal-config-interface]
anymal_gui_resources:
  ubuntu:
    focal: [ros-noetic-anymal-gui-resources]
    noble: [anymal-gui-resources]
anymal_maintainer_tools:
  ubuntu: [anymal-maintainer-tools]
anymal_pc:
  ubuntu: [anymal-pc]
anymal_pc_utils:
  ubuntu: [anymal-pc-utils]
anymal_router:
  ubuntu: [anymal-router]
anymal_software_installer:
  ubuntu: [anymal-software-installer]
anymal_startup_gui:
  ubuntu:
    focal: [ros-noetic-anymal-startup-gui]
    noble: [anymal-startup-gui]
anymal_startup_gui_utils:
  ubuntu: [anymal-startup-gui-utils]
anynspector-firmware:
  ubuntu: [anynspector-firmware]
aptitude:
  ubuntu: [aptitude]
arp-scan:
  ubuntu: [arp-scan]
bash-completion:
  ubuntu: [bash-completion]
bats:
  ubuntu: [bats]
binder:
  ubuntu: [binder]
binder-dev:
  ubuntu: [binder-dev]
catkin:
  ubuntu:
    bionic: [ros-melodic-catkin]
    focal: [ros-noetic-catkin]
cgosdrv-dkms:
  ubuntu: [cgosdrv-dkms]
clang-7:
  ubuntu: [clang-7]
clang-format-7:
  ubuntu: [clang-format-7]
clang-tidy-7:
  ubuntu: [clang-tidy-7]
click-option-group:
  ubuntu: [python3-click-option-group]
clonezilla:
  ubuntu: [clonezilla]
colcon-uv:
  ubuntu: [python3-colcon-uv]
debootstrap:
  ubuntu: [debootstrap]
dosfstools:
  ubuntu: [dosfstools]
fail2ban:
  ubuntu: [fail2ban]
fake-hwclock:
  ubuntu: [fake-hwclock]
flake8:
  ubuntu: [flake8]
flashrom:
  ubuntu: [flashrom]
gas-sensor-board-firmware:
  ubuntu: [gas-sensor-board-firmware]
gazebo:
  ubuntu:
    focal: [gazebo11]
    noble: [gazebo11]
gazebo_msgs:
  ubuntu:
    focal: [ros-noetic-gazebo-msgs]
    noble: [ros-jazzy-gazebo-msgs]
gazebo_plugins:
  ubuntu:
    focal: [ros-noetic-gazebo-plugins]
    noble: [ros-jazzy-gazebo-plugins]
gazebo_ros:
  ubuntu:
    focal: [ros-noetic-gazebo-ros]
    noble: [ros-jazzy-gazebo-ros]
gedit:
  ubuntu: [gedit]
gnupg2:
  ubuntu: [gnupg2]
grpc++:
  ubuntu:
    bionic: [libgrpc++1]
    focal: [libgrpc++1]
    noble: [libgrpc++-dev]
grpc++-dev:
  ubuntu: [libgrpc++-dev]
grpc-web-proxy:
  ubuntu: [grpc-web-proxy]
grub-efi:
  ubuntu: [grub-efi]
hdparm:
  ubuntu: [hdparm]
iftop:
  ubuntu: [iftop]
image_exposure_msgs:
  ubuntu:
    bionic: [ros-melodic-image-exposure-msgs]
    focal: [ros-noetic-image-exposure-msgs]
intel-gpu-tools:
  ubuntu: [intel-gpu-tools]
iotop:
  ubuntu: [iotop]
iperf3:
  ubuntu: [iperf3]
ipython3:
  ubuntu: [ipython3]
jupyter-qtconsole:
  ubuntu: [jupyter-qtconsole]
keyutils:
  ubuntu: [keyutils]
kmod:
  ubuntu: [kmod]
latexmk:
  ubuntu: [latexmk]
libabsl-dev:
  ubuntu: [libabsl-dev]
libabsl20230802:
  ubuntu: [libabsl20230802]
libblosc:
  ubuntu: [libblosc-dev]
libfftw3-dev:
  ubuntu:
    noble: [libfftw3-dev]
libfftw3-double3:
  ubuntu:
    noble: [libfftw3-double3]
libgazebo-dev:
  ubuntu:
    focal: [libgazebo11-dev]
    noble: [libgazebo11-dev]
libgazebo11-dev:
  ubuntu:
    focal: [libgazebo11-dev]
    noble: [libgazebo11-dev]
libgbm:
  ubuntu: [libgbm-dev]
libgtsam-dev:
  ubuntu: [libgtsam-dev]
libgtsam-unstable-dev:
  ubuntu: [libgtsam-unstable-dev]
libirimager:
  ubuntu: [libirimager]
libnss-mdns:
  ubuntu: [libnss-mdns]
libompl-dev:
  ubuntu: [libompl-dev]
libpaho-mqtt.c:
  ubuntu:
    focal: [libpaho-mqtt-dev]
libpaho-mqtt.cpp:
  ubuntu:
    focal: [libpaho-mqttpp-dev]
libpcl-common:
  ubuntu:
    bionic: [libpcl-common1.8]
    focal: [libpcl-common1.8]
libpcl-features:
  ubuntu:
    bionic: [libpcl-features1.8]
    focal: [libpcl-features1.8]
libpcl-filters:
  ubuntu:
    bionic: [libpcl-filters1.8]
    focal: [libpcl-filters1.8]
libpcl-io:
  ubuntu:
    bionic: [libpcl-io1.8]
    focal: [libpcl-io1.8]
libpcl-kdtree:
  ubuntu:
    bionic: [libpcl-kdtree1.8]
    focal: [libpcl-kdtree1.8]
libpcl-segmentation:
  ubuntu:
    bionic: [libpcl-segmentation1.8]
    focal: [libpcl-segmentation1.8]
libpcl-surface:
  debian: [libpcl-surface1.8]
  ubuntu:
    bionic: [libpcl-surface1.8]
    focal: [libpcl-surface1.8]
libpython3.10-dev:
  ubuntu: [libpython3.10-dev]
libpython3.11-dev:
  ubuntu: [libpython3.11-dev]
libpython3.9-dev:
  ubuntu: [libpython3.9-dev]
libqmi-utils:
  ubuntu: [libqmi-utils]
librealsense2-dkms:
  ubuntu: [librealsense2-dkms]
librealsense2-udev-rules:
  ubuntu: [librealsense2-udev-rules]
librealsense2-utils:
  ubuntu: [librealsense2-utils]
libspinnaker:
  ubuntu:
    focal: [libspinnaker]
libspinnaker-dev:
  ubuntu:
    bionic: [libspinnaker1-dev]
    focal: [libspinnaker-dev]
libtorch:
  ubuntu: [libtorch]
libtorch-dev:
  ubuntu: [libtorch-dev]
libxtst6:
  ubuntu: [libxtst6]
linux-lowlatency:
  ubuntu:
    focal: [linux-image-5.4.0-40-lowlatency, linux-headers-5.4.0-40-lowlatency]
    noble: [linux-image-6.8.0-47-lowlatency, linux-headers-6.8.0-47-lowlatency]
livekit-python-sdk:
  ubuntu: [livekit-python-sdk]
livekit-server:
  ubuntu: [livekit-server]
lsb-release:
  ubuntu: [lsb-release]
ltrace:
  ubuntu: [ltrace]
make:
  ubuntu: [make]
memtester:
  ubuntu: [memtester]
modemmanager:
  ubuntu: [modemmanager]
nano:
  ubuntu: [nano]
nautilus:
  ubuntu: [nautilus]
netcat:
  ubuntu: [netcat]
netplan.io:
  ubuntu: [netplan.io]
nginx:
  ubuntu: [nginx]
nload:
  ubuntu: [nload]
onnxruntime-dev:
  ubuntu: [onnxruntime-dev]
p7zip-full:
  ubuntu: [p7zip-full]
parted:
  ubuntu: [parted]
pciutils:
  ubuntu: [pciutils]
pdb-bootloader:
  ubuntu: [pdb-bootloader]
pdb-firmware:
  ubuntu: [pdb-firmware]
pdb_bootloader:
  ubuntu: [pdb-bootloader]
pdb_firmware:
  ubuntu: [pdb-firmware]
plantuml:
  ubuntu: [plantuml]
policykit-1:
  ubuntu: [policykit-1]
prometheus-node-exporter:
  ubuntu: [prometheus-node-exporter]
prometheus-process-exporter:
  ubuntu: [prometheus-process-exporter]
protobuf-compiler-grpc:
  ubuntu: [protobuf-compiler-grpc]
pylint:
  ubuntu: [pylint]
pyside2-tools:
  ubuntu: [pyside2-tools]
pytest-asyncio:
  ubuntu: [python3-pytest-asyncio]
pytest-mock:
  ubuntu: [python3-pytest-mock]
python-cvxopt:
  ubuntu: [python-cvxopt]
python-igraph:
  ubuntu: [python-igraph]
python-progressbar:
  ubuntu: [python-progressbar]
python-psutil:
  ubuntu: [python-psutil]
python-reportlab:
  ubuntu: [python-reportlab]
python-rospkg:
  ubuntu: [python-rospkg]
python-serial:
  ubuntu: [python-serial]
python3-apriltag:
  ubuntu: [python3-apriltag]
python3-apt:
  ubuntu: [python3-apt]
python3-asteval:
  ubuntu: [python3-asteval]
python3-certifi:
  ubuntu: [python3-certifi]
python3-cgroupspy:
  ubuntu: [python3-cgroupspy]
python3-croniter:
  ubuntu: [python3-croniter]
python3-elementpath:
  ubuntu: [python3-elementpath]
python3-evo:
  ubuntu: [python3-evo]
python3-fabric:
  ubuntu: [python3-fabric]
python3-flask-httpauth:
  ubuntu: [python3-flask-httpauth]
python3-flask-restful:
  ubuntu: [python3-flask-restful]
python3-freezegun:
  ubuntu: [python3-freezegun]
python3-genpy:
  ubuntu: [python3-genpy]
python3-gphoto2:
  ubuntu: [python3-gphoto2]
python3-grpcio:
  ubuntu:
    bionic: [python3-grpcio]
    focal: [python3-grpcio]
    noble: [python3-grpcio]
python3-ifaddr:
  ubuntu: [python3-ifaddr]
python3-igraph:
  ubuntu: [python3-igraph]
python3-invoke:
  ubuntu: [python3-invoke]
python3-ipykernel:
  ubuntu: [python3-ipykernel]
python3-nmap:
  ubuntu: [python3-nmap]
python3-progressbar:
  ubuntu: [python3-progressbar]
python3-protobuf:
  ubuntu:
    bionic: [python3-protobuf]
    focal: [python3-protobuf]
    noble: [python3-protobuf]
python3-psutil:
  ubuntu: [python3-psutil]
python3-pycountry:
  ubuntu: [python3-pycountry]
python3-pympler:
  ubuntu: [python3-pympler]
python3-pyside2.qtprintsupport:
  ubuntu: [python3-pyside2.qtprintsupport]
python3-qtconsole:
  ubuntu: [python3-qtconsole]
python3-regex:
  ubuntu: [python3-regex]
python3-reportlab:
  ubuntu: [python3-reportlab]
python3-rosbag:
  ubuntu: [python3-rosbag]
python3-rospkg:
  ubuntu: [python3-rospkg]
python3-rospy:
  ubuntu: [python3-rospy]
python3-rospycgosdrv-dkms:
  ubuntu: [python3-rospycgosdrv-dkms]
python3-rostopic:
  ubuntu: [python3-rostopic]
python3-ruamel.yaml:
  ubuntu: [python3-ruamel.yaml]
python3-scipy:
  ubuntu: [python3-scipy]
python3-serial:
  ubuntu: [python3-serial]
python3-urllib3:
  ubuntu: [python3-urllib3]
python3-xdg:
  ubuntu: [python3-xdg]
python3-xmlschema:
  ubuntu: [python3-xmlschema]
python3.10:
  ubuntu: [python3.10]
python3.10-venv:
  ubuntu: [python3.10-venv]
python3.11:
  ubuntu: [python3.11]
python3.11-venv:
  ubuntu: [python3.11-venv]
python3.9:
  ubuntu: [python3.9]
python3.9-venv:
  ubuntu: [python3.9-venv]
qttools5-dev:
  ubuntu: [qttools5-dev]
ros_rtsp:
  ubuntu:
    focal: [ros-noetic-ros-rtsp]
# Fixme: packages below are a workaround for upstream ros packages not yet available in noetic. Remove once they are.
serial:
  ubuntu:
    bionic: [ros-melodic-serial]
    focal: [ros-noetic-serial]
shutter:
  ubuntu: [shutter]
sierra-wireless-firmware:
  ubuntu: [sierra-wireless-firmware]
soci-dev:
  debian: [libsoci-dev]
  ubuntu:
    bionic: [libsoci-dev]
    focal: [libsoci-dev]
soci-postgresql3.2:
  debian: [libsoci-postgresql3.2]
  ubuntu:
    bionic: [libsoci-postgresql3.2v5]
    focal: [libsoci-postgresql3.2v5]
# Package in anybotics/third_party_packaging with the firmware and update script for Sorama acoustic camera.
sorama_firmware:
  ubuntu: [sorama-firmware]
speedtest:
  ubuntu: [speedtest]
spinnaker:
  ubuntu: [spinnaker]
spinview:
  ubuntu:
    bionic: [spinview-qt1]
    focal: [spinview-qt]
sshfs:
  ubuntu: [sshfs]
statistics_msgs:
  ubuntu:
    bionic: [ros-melodic-statistics-msgs]
    focal: [ros-noetic-statistics-msgs]
strace:
  ubuntu: [strace]
sysbench:
  ubuntu: [sysbench]
systemd:
  ubuntu: [systemd]
systemd-coredump:
  ubuntu: [systemd-coredump]
tensorflow:
  ubuntu:
    noble: [tensorflow]
texlive-extra-utils:
  ubuntu: [texlive-extra-utils]
texlive-xetex:
  ubuntu: [texlive-xetex]
ucf:
  ubuntu: [ucf]
velodyne_description:
  ubuntu:
    bionic: [ros-melodic-velodyne-description]
    focal: [ros-noetic-velodyne-description]
velodyne_gazebo_plugins:
  ubuntu:
    bionic: [ros-melodic-velodyne-gazebo-plugins]
    focal: [ros-noetic-velodyne-gazebo-plugins]
vmagent:
  ubuntu: [vmagent]
wcb-openwrt:
  ubuntu: [wcb-openwrt]
weasyprint:
  ubuntu: [weasyprint]
wfov_camera_msgs:
  ubuntu:
    bionic: [ros-melodic-wfov-camera-msgs]
    focal: [ros-noetic-wfov-camera-msgs]
xauth:
  ubuntu: [xauth]
zstd:
  ubuntu: [zstd]
